### ISSUE TITLE
No generation of the README.md withing "leetcode" folder

### ISSUE THREAD

**Issue by fcaponetto** [JacobLinCool/LeetCode-Dump#10]
Hi @JacobLinCool. 

Thank you for your efforts in developing this dumper. However, I encountered an issue. On my Leetcode profile, I noticed that there are fewer available solutions than submitted. Consequently, when I run the following command:
```
docker run --rm -v $(pwd)/leetcode:/leetcode jacoblincool/leetcode-dump -s "xyz"
```
It doesn't generate the README.md file within the leetcode folder, unlike what is observed in your [LeetCode-Solutions](https://github.com/JacobLinCool/LeetCode-Solutions) repository.

![image](https://github.com/JacobLinCool/LeetCode-Dump/assets/11439681/723b52f8-6c59-45a5-9777-6be4982a67f5)
![image](https://github.com/JacobLinCool/LeetCode-Dump/assets/11439681/1a09241e-d7a8-47bc-a753-5d256b113b1d)

The aforementioned issue leads to an error when I  try to build the solutions as a static website
```
docker run --rm -v $(pwd)/leetcode:/leetcode -v $(pwd)/site:/site jacoblincool/leetcode-dump build
```
Error message
```
[Transform] Error: ENOENT: no such file or directory, open '/leetcode/README.md'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at transform (/leetcode-dump/lib/leetcode-dump.js:174:127)
    at build (/leetcode-dump/lib/leetcode-dump.js:223:3)
    at Command.<anonymous> (/leetcode-dump/lib/leetcode-dump.js:460:3)
    at Command.listener [as _actionHandler] (/leetcode-dump/node_modules/.pnpm/commander@9.0.0/node_modules/commander/lib/command.js:480:17)
    at /leetcode-dump/node_modules/.pnpm/commander@9.0.0/node_modules/commander/lib/command.js:1234:65
    at Command._chainOrCall (/leetcode-dump/node_modules/.pnpm/commander@9.0.0/node_modules/commander/lib/command.js:1151:12)
    at Command._parseCommand (/leetcode-dump/node_modules/.pnpm/commander@9.0.0/node_modules/commander/lib/command.js:1234:27)
    at Command._dispatchSubcommand (/leetcode-dump/node_modules/.pnpm/commander@9.0.0/node_modules/commander/lib/command.js:1057:25) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/leetcode/README.md'
}
```
Not fully sure if the root of the issue is the missing README.md or elsewhere. I just guessed it was the missing file because the above error message.

Thanks in advance for any help :smile:

**Comment by fcaponetto** [comment]
After delving into the code, I believe I've addressed the issue. :smiley: 

I made slight adjustments to the `submissions query` in order to retrieve only the available submissions. The relevant updated `Leetcode-Query` version can be found [here](https://github.com/fcaponetto/LeetCode-Query/blob/f091cda16c032d36862f7d5a0064d679677a69fc/src/leetcode.ts#L149).

The modified `submission query` function is utilized [here](https://github.com/fcaponetto/LeetCode-Dump/blob/25d88ea01ceb6c46be7d2992b58a2f9afab108f8/src/dump.ts#L233), accompanied by some minor changes.

If you deem these changes are significant for the main repository, I'm eager to open a PR to include all of them.
